### ISSUE TITLE
AttributeError: type object 'Callable' has no attribute '_abc_registry' while installation

### ISSUE THREAD

**Issue by tonychenxyz** [lyft/l5kit#187]
Hi!

I encountered the following error while trying pip install l5kit as well as installing as a developer.

```
ERROR: Command errored out with exit status 1:
   command: /home/tonychenxyz/anaconda3/envs/torch1.6/bin/python /home/tonychenxyz/anaconda3/envs/torch1.6/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-vgrf1i5t/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple --find-links https://download.pytorch.org/whl/torch_stable.html -- setuptools wheel
       cwd: None
  Complete output (42 lines):
  Traceback (most recent call last):
    File "/home/tonychenxyz/anaconda3/envs/torch1.6/lib/python3.7/runpy.py", line 193, in _run_module_as_main
      "__main__", mod_spec)
    File "/home/tonychenxyz/anaconda3/envs/torch1.6/lib/python3.7/runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "/home/tonychenxyz/anaconda3/envs/torch1.6/lib/python3.7/site-packages/pip/__main__.py", line 26, in <module>
      sys.exit(_main())
    File "/home/tonychenxyz/anaconda3/envs/torch1.6/lib/python3.7/site-packages/pip/_internal/cli/main.py", line 73, in main
      command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
    File "/home/tonychenxyz/anaconda3/envs/torch1.6/lib/python3.7/site-packages/pip/_internal/commands/__init__.py", line 104, in create_command
      module = importlib.import_module(module_path)
    File "/home/tonychenxyz/anaconda3/envs/torch1.6/lib/python3.7/importlib/__init__.py", line 127, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
    File "<frozen importlib._bootstrap>", line 983, in _find_and_load
    File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 728, in exec_module
    File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    File "/home/tonychenxyz/anaconda3/envs/torch1.6/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 17, in <module>
      from pip._internal.cli.req_command import RequirementCommand, with_cleanup
    File "/home/tonychenxyz/anaconda3/envs/torch1.6/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 16, in <module>
      from pip._internal.index.collector import LinkCollector
    File "/home/tonychenxyz/anaconda3/envs/torch1.6/lib/python3.7/site-packages/pip/_internal/index/collector.py", line 14, in <module>
      from pip._vendor import html5lib, requests
    File "/home/tonychenxyz/anaconda3/envs/torch1.6/lib/python3.7/site-packages/pip/_vendor/requests/__init__.py", line 125, in <module>
      from . import utils
    File "/home/tonychenxyz/anaconda3/envs/torch1.6/lib/python3.7/site-packages/pip/_vendor/requests/utils.py", line 25, in <module>
      from . import certs
    File "/home/tonychenxyz/anaconda3/envs/torch1.6/lib/python3.7/site-packages/pip/_vendor/requests/certs.py", line 15, in <module>
      from pip._vendor.certifi import where
    File "/home/tonychenxyz/anaconda3/envs/torch1.6/lib/python3.7/site-packages/pip/_vendor/certifi/__init__.py", line 1, in <module>
      from .core import contents, where
    File "/home/tonychenxyz/anaconda3/envs/torch1.6/lib/python3.7/site-packages/pip/_vendor/certifi/core.py", line 12, in <module>
      from importlib.resources import path as get_path, read_text
    File "/home/tonychenxyz/anaconda3/envs/torch1.6/lib/python3.7/importlib/resources.py", line 11, in <module>
      from typing import Iterable, Iterator, Optional, Set, Union   # noqa: F401
    File "/home/tonychenxyz/anaconda3/envs/torch1.6/lib/python3.7/site-packages/typing.py", line 1357, in <module>
      class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
    File "/home/tonychenxyz/anaconda3/envs/torch1.6/lib/python3.7/site-packages/typing.py", line 1005, in __new__
      self._abc_registry = extra._abc_registry
  AttributeError: type object 'Callable' has no attribute '_abc_registry'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /home/tonychenxyz/anaconda3/envs/torch1.6/bin/python /home/tonychenxyz/anaconda3/envs/torch1.6/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-vgrf1i5t/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple --find-links https://download.pytorch.org/whl/torch_stable.html -- setuptools wheel Check the logs for full command output.
```

**Comment by tonychenxyz** [comment]
Problem solved by pip uninstall typing
