### ISSUE TITLE
ValueError:  track_id 259 not in frame or below threshold

### ISSUE THREAD

**Issue by yousef-xailient** [lyft/l5kit#200]
I create a chopped dataset using chop_dataset.py, then I use the generated mask to create an Agent Dataset.

I am getting an error as below.

File "/home/yousef/miniconda3/envs/lyft/lib/python3.8/site-packages/tqdm/std.py", line 1133, in __iter__
    for obj in iterable:
  File "/home/yousef/miniconda3/envs/lyft/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/home/yousef/miniconda3/envs/lyft/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 989, in _next_data
    return self._process_data(data)
  File "/home/yousef/miniconda3/envs/lyft/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1014, in _process_data
    data.reraise()
  File "/home/yousef/miniconda3/envs/lyft/lib/python3.8/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/yousef/miniconda3/envs/lyft/lib/python3.8/site-packages/l5kit/sampling/agent_sampling.py", line 109, in generate_agent_sample
    agent = filter_agents_by_track_id(
IndexError: index 0 is out of bounds for axis 0 with size 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yousef/miniconda3/envs/lyft/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/yousef/miniconda3/envs/lyft/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/yousef/miniconda3/envs/lyft/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/yousef/deep-learning/kaggle/lyft/datasets/regression.py", line 45, in __getitem__
    data = self.dataset[idx]
  File "/home/yousef/miniconda3/envs/lyft/lib/python3.8/site-packages/l5kit/dataset/agent.py", line 115, in __getitem__
    return self.get_frame(scene_index, state_index, track_id=track_id)
  File "/home/yousef/miniconda3/envs/lyft/lib/python3.8/site-packages/l5kit/dataset/ego.py", line 98, in get_frame
    data = self.sample_function(state_index, frames, self.dataset.agents, tl_faces, track_id)
  File "/home/yousef/miniconda3/envs/lyft/lib/python3.8/site-packages/l5kit/sampling/agent_sampling.py", line 113, in generate_agent_sample
    raise ValueError(f" track_id {selected_track_id} not in frame or below threshold")
ValueError:  track_id 259 not in frame or below threshold

Any idea what's going on?

**Comment by yousef-xailient** [comment]
I forgot to change val_data_loader key to scenes/validate_chopped_100/validate.zarr. It was still scenes/validate.zarr. Closing this.
