### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by johnwlambert** [lyft/l5kit#46]
Thanks very much for this contribution to the research community and for this devkit. A few assorted questions about the 1001 hours dataset:

(1) Would it be possible to add the rendered notebooks with output in Github, rather than just the [code](https://github.com/lyft/l5kit/blob/master/examples/visualisation/visualise_data.ipynb)?
(2) Would you all be able to make a map notebook, to better understand the format, e.g. road vs. lane geometry, like [this notebook](https://github.com/argoai/argoverse-api/blob/master/demo_usage/argoverse_map_tutorial.ipynb)?
(3) To what precision is the aerial imagery aligned with the published map? It looks like Page Mill Road's road geometry doesn't align with the aerial map [here](https://arxiv.org/pdf/2006.14480.pdf):

<img width="654" alt="Screen Shot 2020-07-02 at 11 08 18 AM" src="https://user-images.githubusercontent.com/16724970/86376019-6b32fd80-bc54-11ea-9a95-79f1da99bc7d.png">

(4) I ran into the following bug when installing requirements on Mac when I follow the setup instructions at `pip install -r requirements.txt`

```
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/m9/l00nd84d453fcx907pmlyd2h0000gq/T/pip-install-3ua4_jeg/numcodecs/setup.py", line 362, in <module>
      run_setup(with_extensions)
    File "/private/var/folders/m9/l00nd84d453fcx907pmlyd2h0000gq/T/pip-install-3ua4_jeg/numcodecs/setup.py", line 355, in run_setup
      license='MIT',
    File "/Users/johnlamb/miniconda3/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/Users/johnlamb/miniconda3/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/Users/johnlamb/miniconda3/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/Users/johnlamb/miniconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/Users/johnlamb/miniconda3/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 192, in run
      self.run_command('build')
    File "/Users/johnlamb/miniconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/Users/johnlamb/miniconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/Users/johnlamb/miniconda3/lib/python3.7/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/Users/johnlamb/miniconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/Users/johnlamb/miniconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/private/var/folders/m9/l00nd84d453fcx907pmlyd2h0000gq/T/pip-install-3ua4_jeg/numcodecs/setup.py", line 279, in run
      build_ext.run(self)
    File "/Users/johnlamb/miniconda3/lib/python3.7/distutils/command/build_ext.py", line 340, in run
      self.build_extensions()
    File "/Users/johnlamb/miniconda3/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
      self._build_extensions_serial()
    File "/Users/johnlamb/miniconda3/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
      self.build_extension(ext)
    File "/private/var/folders/m9/l00nd84d453fcx907pmlyd2h0000gq/T/pip-install-3ua4_jeg/numcodecs/setup.py", line 289, in build_extension
      raise BuildFailed()
  __main__.BuildFailed
  
  ----------------------------------------
  Failed building wheel for numcodecs
  Running setup.py clean for numcodecs
Failed to build numcodecs
awscli 1.16.209 has requirement colorama<=0.3.9,>=0.2.5, but you'll have colorama 0.4.3 which is incompatible.
readme-renderer 26.0 has requirement Pygments>=2.5.1, but you'll have pygments 2.4.0 which is incompatible.
```
and
```
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/m9/l00nd84d453fcx907pmlyd2h0000gq/T/pip-install-3ua4_jeg/numcodecs/setup.py", line 362, in <module>
        run_setup(with_extensions)
      File "/private/var/folders/m9/l00nd84d453fcx907pmlyd2h0000gq/T/pip-install-3ua4_jeg/numcodecs/setup.py", line 355, in run_setup
        license='MIT',
      File "/Users/johnlamb/miniconda3/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/Users/johnlamb/miniconda3/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/Users/johnlamb/miniconda3/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/Users/johnlamb/miniconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/Users/johnlamb/miniconda3/lib/python3.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/Users/johnlamb/miniconda3/lib/python3.7/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/Users/johnlamb/miniconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Users/johnlamb/miniconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/Users/johnlamb/miniconda3/lib/python3.7/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/Users/johnlamb/miniconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Users/johnlamb/miniconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/private/var/folders/m9/l00nd84d453fcx907pmlyd2h0000gq/T/pip-install-3ua4_jeg/numcodecs/setup.py", line 279, in run
        build_ext.run(self)
      File "/Users/johnlamb/miniconda3/lib/python3.7/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/Users/johnlamb/miniconda3/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
        self._build_extensions_serial()
      File "/Users/johnlamb/miniconda3/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
        self.build_extension(ext)
      File "/private/var/folders/m9/l00nd84d453fcx907pmlyd2h0000gq/T/pip-install-3ua4_jeg/numcodecs/setup.py", line 289, in build_extension
        raise BuildFailed()
    __main__.BuildFailed
    
    ----------------------------------------
Command "/Users/johnlamb/miniconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/m9/l00nd84d453fcx907pmlyd2h0000gq/T/pip-install-3ua4_jeg/numcodecs/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/m9/l00nd84d453fcx907pmlyd2h0000gq/T/pip-record-z8wxw4rd/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/m9/l00nd84d453fcx907pmlyd2h0000gq/T/pip-install-3ua4_jeg/numcodecs/
```

**Comment by lucabergamini** [comment]
Hi @johnwlambert; L5Kit is still an early release so hopefully a lot of what you suggest will be there soon :) 


> (1) Would it be possible to add the rendered notebooks with output in Github, rather than just the [code](https://github.com/lyft/l5kit/blob/master/examples/visualisation/visualise_data.ipynb)?

Having the output in GitHub is a little bit tricky, especially if you want to keep them updated (even now jupyter makes some slight changes like the python version or other metadata). Maybe once the examples will get enough mature adding it won't be that cumbersome.



> (2) Would you all be able to make a map notebook, to better understand the format, e.g. road vs. lane geometry, like [this notebook](https://github.com/argoai/argoverse-api/blob/master/demo_usage/argoverse_map_tutorial.ipynb)?

We don't have that granularity yet, but given that those operations are performed in the code we'll do that if enough interest arises.



> (3) To what precision is the aerial imagery aligned with the published map? It looks like Page Mill Road's road geometry doesn't align with the aerial map [here](https://arxiv.org/pdf/2006.14480.pdf):

I can't give you an exact number, but we're working to improve that. We're aware semantic and satellite don't match exactly.

> (4) I ran into the following bug when installing requirements on Mac when I follow the setup instructions at `pip install -r requirements.txt`

`numcodecs` is a `zarr` dependency and contains, among other, the `blosc` compressor. As far as I know it's implemented in C++ so it may have some system dependencies. You can maybe try to update pip as the latest version may have a pre-compiled wheel for [that](https://github.com/zarr-developers/numcodecs/issues/70)

**Comment by johnwlambert** [comment]
Thanks for the quick reply Luca. I found I was able to push rendered IPython [notebooks](https://github.com/argoai/argoverse-api/blob/master/demo_usage/argoverse_map_tutorial.ipynb) to Git without much trouble by just saving and committing the file after running all cells.

**Comment by lucabergamini** [comment]
> I found I was able to push rendered IPython [notebooks](https://github.com/argoai/argoverse-api/blob/master/demo_usage/argoverse_map_tutorial.ipynb) to Git without much trouble by just saving and committing the file after running all cells

yeah but the issue is not pushing them, is keeping them updated. The output cells are build artefacts, and as such it's not a good idea to upload them unless the notebook is very very stable. When things will get stable, we'll consider it.



> I found updating my `pip` installation didn't resolve those installation errors.

you can try to install only `zarr` in a new env (`pip install zarr`). If that doesn't work, I suggest you to head to the zarr/numcodecs [GitHub](https://github.com/zarr-developers/numcodecs) and ask there for support. zarr can run on mac, so I suspect it might be a system dependencies issue...

**Comment by pondruska** [comment]
Hi @johnwlambert, regarding the alignment in the figure:

The figure in the paper was aligned manually in adobe illustrator so there is some alignment gap we will fix in the next update. Thanks for pointing this out! This affects only the paper if you actually run the code rasterizes the two maps - aerial and semantic should be aligned very closely (< 1m error).

**Comment by johnwlambert** [comment]
That's good to know, thanks @pondruska.
